### PR TITLE
Build To-Do List Structure (rm)

### PR DESCRIPTION
**Pull request by Jord4N-AC**
> _**I'm repeating this module**_
In this project, I built a simple HTML list of To-Do tasks. The list was styled according to the specifications,  The list was built using webpack and served by a webpack dev server.

### Requirements
- Set up the project with webpack
- Create an index.html file, Create a placeholder (div or ul element) for list items
- Set the index.html as a template using the HTML Webpack Plugin
- Create an index.js file, and create an array of objects, each object contains:
  - description [string]
  - completed [bool]
  - index: [number]
- Create a function to iterate over the array and render the list on the page
- Create a style.css and style the To-Do List, set up Webpack Style/CSS Loader to load style from there
- All source files (index.html, index.js, and style.css) are located in /src directory and distribution files are generated by webpack and served by webpack dev server

### General Requirements

- Check linter errors
- Use the correct GitHub flow
- Document my work in a professional way
- Follow best practices for HTML, CSS & JavaScript
- Open a pull request and ask for a review

### CODE REVIEW

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @Jord4N-AC ,  

Your project is complete! 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 


giphy

- [ ] OPTIONAL: I noticed that for this milestone you went over the requirements and submitted a completed project, perhaps you are repeating module. Page looks awesome and all the functionality works, however, I strongly suggest submitting only requested functionality. Because, for the current milestone you are supposed to have a static list array, but yours is already dynamic (which is works perfectly well !). 
If you completed the project you can checkout to the first commit and open a new branch, then keep merging there all the changes 😉 

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Jord4N-AC** [comment]
@ShoiraTa

**Comment by Jord4N-AC** [comment]
@ShoiraTa
Is it possible to create a branch from a commit and then merge that again?

**Comment by ShoiraTa** [comment]
hey, @Jord4N-AC, What I was recommending is, you could checkout two  branches from the first commit, one would be the `development-new` branch, and the second `feature-new` to complete milestones, then you could keep merging branches` feature-old` with `feature-new`, after approval merge `feature-new` with  `development-new`

**Comment by Jord4N-AC** [comment]
@ShoiraTa
Now It's clear, I understand it
Thank you
Thanks for the review, too

**Pull request merged**
