### PR TITLE
To Do list add & remove Feature (rm)

### PR DESCRIPTION
**Pull request by Jord4N-AC**
> **As I'm repeating this module I just have made some changes in my code to improve functionality, reduce repetitions, and make it more readable.**

In this project, I implemented the CRUD (create, update, delete) methods. All the elements of the user interface are fully functional, details are below.

### Requirements & Features

- Use webpack to bundle JavaScript
- Use proper ES6 syntax
- Use ES6 modules to write modular JavaScript
___
- Create a JavaScript file for the new functionality
- Implement a function for adding a new task (add a new element to the array)
- Implement a function for deleting a task (remove an element from the array)
- Implement a function for editing task descriptions (update content on the array)
- By default, new tasks have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5)
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the next task(2) should be set to 1)
- All changes to the To-Do List are saved in local storage

### General Requirements:

- Check linter errors
- Use the correct GitHub flow
- Document my work in a professional way
- Follow best practices for HTML, CSS & JavaScript
- Open a pull request and ask for a review

### CODE REVIEW

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi, @Jord4N-AC 👋, 

Good job so far! I must commend you for the great work done. The UI implementation when you add a task is very nice and also ensuring tasks can not be duplicated is great. Kudos. 👏 

## Highlights
- Implemented a function for adding tasks 💯 
- Implemented a function for removing tasks 💯 
- Implemented a function for editing tasks 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
I am giving my comments here because I can't comment on the necessary files due to their absence in this section of the pull request.
- When you add a task, the `task.index` should start from 1, i.e the length of the array + 1 and not 0. Kindly implement that in your save_data.js file. 👍
- When you remove a task and reorder the index key for each task, the index key should be equal to the length of the array + 1. Kindly implement that in the remove_task.js file. 👍  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- You can also consider implementing the edit function in such a way that when I press enter, the task's `description` is updated and saved instead of having to click outside the task for it to be updated. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Jord4N-AC** [comment]
@Gambit142
Thank you so much for your review
I'll implement require changes

**Comment by Gambit142** [comment]
@Jord4N-AC, Great job, once again. and you are welcome 👍

**Review by Emmyn5600 — APPROVED** [review]
Hi @Jord4N-AC 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
